package net.acprog.ide.utils.event;

public enum EventType {
    PROJECT_CREATE,
    PROJECT_OPEN,
    PROJECT_PRE_SAVE,
    PROJECT_SAVE,
    PREFERENCES_OPEN,
    COMPONENT_CREATE,
    COMPONENT_SELECTED,
    COMPILE,
    COMPILE_AND_RUN,
    HELP_ABOUT,
    HELP_UPDATE,
    HELP_SLACK,
    VISUAL_EDITOR_UPDATEUI, BUILD, VERIFY, UPLOAD, QUIT
}
