package net.acprog.ide.utils.event;

public enum EventType {
    EVENT_PROJECT_CREATE,
    EVENT_PROJECT_OPEN,
    EVENT_PROJECT_SAVE,
    EVENT_PREFERENCES,
    EVENT_QUIT,
    EVENT_COMPONENT_SELECTED,
    EVENT_COMPILE,
    EVENT_HELP_ABOUT, EVENT_HELP_UPDATE, EVENT_HELP_SLACK, EVENT_COMPILE_AND_RUN
}
