package net.acprog.ide.gui;

import net.acprog.ide.App;
import net.acprog.ide.configurations.IdeSettingsProject;

import javax.swing.*;
import java.awt.*;
import java.io.File;

public class OpenFrame extends JDialog {

    public OpenFrame() {
        setLayout(new BorderLayout());
        setTitle("Open project");
        setModal(true);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        initComponents();

        newProjectLocation.setEditable(false);
        newProjectLocationSelection.addActionListener(e -> {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.addActionListener(e1 -> {
                File selection = fc.getSelectedFile();
                if (selection != null && selection.isDirectory()) {
                    newProjectLocation.setText(selection.getAbsolutePath());
                }
            });
            fc.setDialogTitle("Select where project folder should be located");
            fc.showOpenDialog(OpenFrame.this);
        });
        newProjectButton.addActionListener(e -> {
            try {
                IdeSettingsProject project = IdeSettingsProject.createNewProject(new File(newProjectLocation.getText()), newProjectName.getText());
                OpenFrame.this.dispose();
                App.openProject(project);
            } catch (Exception e1) {
                e1.printStackTrace();
            }
        });

        openProjectLocation.setEditable(false);
        openProjectLocationSelection.addActionListener(e -> {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.addActionListener(e1 -> {
                File selection = fc.getSelectedFile();
                if (selection != null && selection.isDirectory()) {
                    openProjectLocation.setText(selection.getAbsolutePath());
                }
            });
            fc.setDialogTitle("Select where your project folder is located");
            fc.showOpenDialog(OpenFrame.this);
        });
        openProjectButton.addActionListener(e -> {
            IdeSettingsProject project = IdeSettingsProject.fromFile(new File(openProjectLocation.getText()));
            OpenFrame.this.dispose();
            App.openProject(project);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        createProjectPanel = new javax.swing.JPanel();
        newProjectName = new javax.swing.JTextField();
        newProjectLocation = new javax.swing.JTextField();
        newProjectLocationSelection = new javax.swing.JButton();
        newProjectNameLabel = new javax.swing.JLabel();
        newProjectLocationLabel = new javax.swing.JLabel();
        newProjectButton = new javax.swing.JButton();
        openProjectPanel = new javax.swing.JPanel();
        openProjectLocation = new javax.swing.JTextField();
        openProjectLocationSelection = new javax.swing.JButton();
        openProjectButton = new javax.swing.JButton();
        openProjectLocationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        createProjectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Create new project"));

        newProjectLocationSelection.setText("...");

        newProjectNameLabel.setText("Project name");

        newProjectLocationLabel.setText("Project location");

        newProjectButton.setText("Create");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(createProjectPanel);
        createProjectPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(newProjectNameLabel)
                                        .addComponent(newProjectLocationLabel))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(newProjectButton)
                                                .addGap(0, 244, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(newProjectLocation)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newProjectLocationSelection))
                                        .addComponent(newProjectName))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newProjectNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newProjectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newProjectLocationSelection)
                                        .addComponent(newProjectLocationLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newProjectButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        openProjectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Open existing project"));

        openProjectLocationSelection.setText("...");

        openProjectButton.setText("Open");

        openProjectLocationLabel.setText("Project location");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(openProjectPanel);
        openProjectPanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(openProjectLocationLabel)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(openProjectButton)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(openProjectLocation)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(openProjectLocationSelection)))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(openProjectLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(openProjectLocationSelection)
                                        .addComponent(openProjectLocationLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openProjectButton)
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(createProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(openProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JButton newProjectLocationSelection;
    private javax.swing.JButton newProjectButton;
    private javax.swing.JButton openProjectLocationSelection;
    private javax.swing.JButton openProjectButton;
    private javax.swing.JLabel newProjectNameLabel;
    private javax.swing.JLabel newProjectLocationLabel;
    private javax.swing.JLabel openProjectLocationLabel;
    private javax.swing.JPanel createProjectPanel;
    private javax.swing.JPanel openProjectPanel;
    private javax.swing.JTextField newProjectName;
    private javax.swing.JTextField newProjectLocation;
    private javax.swing.JTextField openProjectLocation;
    // End of variables declaration

}
